### ISSUE TITLE
Hands on - Re-write

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-leaflet#13]
At: https://ubc-library-rc.github.io/gis-intro-leaflet/content/hands-on.html

I found some phrases a bit confusing, re-wrote it bellow.

"Putting it into Perspective
Before we start working on our map, let’s just put things into perspective. This is an introductory workshop, and meant to get you started **with the tools and give you the skills to move forward on your own. Within the greater web mapping ecosystem, we’re touching on the essentials. And give you an idea of how what we are doing fits into that ecosystem,** (...)"

Putting it into Perspective
Before we start working on our map, let’s just put things into perspective: This is an introductory workshop meant to get you started with the tools and skills to move forward on your own. Within the greater web mapping ecosystem, we’re touching on the essentials. To give you an idea of how what we are doing fits into that ecosystem, take a look at this diagram from Maptime, and notice the <HTML> document, and the internet browser.

**Comment by ect123** [comment]
How about this?    

Before we start working on our map, let’s just put things into perspective: This is an introductory workshop meant to get you started with the tools and skills to move forward on your own. Within the greater web mapping ecosystem context, we’re touching on the essentials. To give you an idea of where this workshop fits into that ecosystem, take a look at this diagram from [Maptime](http://maptime.io/). Note the .html document and the internet browser.
