### ISSUE TITLE
Introduction - Prerequisites - Question

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-leaflet#8]
"Making maps is hard. And without practice, working in the web is hard too. **While there are no actual prerequisites for the in person workshop**" Are there any for the online workshop?

**Comment by ect123** [comment]
Good catch. I think my original intent was to provide this as a disclaimer for asynchronous learners, but it is still the same as an in-person session. Let's omit the words "the in person" and add the word "this".
